function mountains() {
         document.getElementById('mountains').style.cssText = "opacity: 1; z-index: 1;";
         document.getElementById('desert').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('lake').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('wood').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('water').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('contacts').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('menu_mountains').style.backgroundColor = 'rgba(0,0,0,.75)';
         document.getElementById('menu_desert').style.backgroundColor = '';
         document.getElementById('menu_lake').style.backgroundColor = '';
         document.getElementById('menu_wood').style.backgroundColor = '';
         document.getElementById('menu_water').style.backgroundColor = '';
         document.getElementById('menu_contacts').style.backgroundColor = '';
     };
     function desert() {
         document.getElementById('mountains').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('desert').style.cssText = "opacity: 1; z-index: 1;";
         document.getElementById('lake').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('wood').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('water').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('contacts').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('menu_mountains').style.backgroundColor = '';
         document.getElementById('menu_desert').style.backgroundColor = 'rgba(0,0,0,.75)';
         document.getElementById('menu_lake').style.backgroundColor = '';
         document.getElementById('menu_wood').style.backgroundColor = '';
         document.getElementById('menu_water').style.backgroundColor = '';
         document.getElementById('menu_contacts').style.backgroundColor = '';
     };
     function lake() {
         document.getElementById('mountains').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('desert').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('lake').style.cssText = "opacity: 1; z-index: 1;";
         document.getElementById('wood').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('water').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('contacts').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('menu_mountains').style.backgroundColor = '';
         document.getElementById('menu_desert').style.backgroundColor = '';
         document.getElementById('menu_lake').style.backgroundColor = 'rgba(0,0,0,.75)';
         document.getElementById('menu_wood').style.backgroundColor = '';
         document.getElementById('menu_water').style.backgroundColor = '';
         document.getElementById('menu_contacts').style.backgroundColor = '';
     };
     function wood() {
         document.getElementById('mountains').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('desert').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('lake').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('wood').style.cssText = "opacity: 1; z-index: 1;";
         document.getElementById('water').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('contacts').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('menu_mountains').style.backgroundColor = '';
         document.getElementById('menu_desert').style.backgroundColor = '';
         document.getElementById('menu_lake').style.backgroundColor = '';
         document.getElementById('menu_wood').style.backgroundColor = 'rgba(0,0,0,.75)';
         document.getElementById('menu_water').style.backgroundColor = '';
         document.getElementById('menu_contacts').style.backgroundColor = '';
     };
     function water() {
         document.getElementById('mountains').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('desert').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('lake').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('wood').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('water').style.cssText = "opacity: 1; z-index: 1;";
         document.getElementById('contacts').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('menu_mountains').style.backgroundColor = '';
         document.getElementById('menu_desert').style.backgroundColor = '';
         document.getElementById('menu_lake').style.backgroundColor = '';
         document.getElementById('menu_wood').style.backgroundColor = '';
         document.getElementById('menu_water').style.backgroundColor = 'rgba(0,0,0,.75)';
         document.getElementById('menu_contacts').style.backgroundColor = '';
     };
     function contacts() {
         document.getElementById('mountains').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('desert').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('lake').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('wood').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('water').style.cssText = "opacity: 0; z-index: 0;";
         document.getElementById('contacts').style.cssText = "opacity: 1; z-index: 1;";
         document.getElementById('menu_mountains').style.backgroundColor = '';
         document.getElementById('menu_desert').style.backgroundColor = '';
         document.getElementById('menu_lake').style.backgroundColor = '';
         document.getElementById('menu_wood').style.backgroundColor = '';
         document.getElementById('menu_water').style.backgroundColor = '';
         document.getElementById('menu_contacts').style.backgroundColor = 'rgba(0,0,0,.75)';
     };
